#!/bin/sh
 
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs devtmpfs /dev

exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console

adduser -D Arthur
adduser -D Morgen
adduser -D John
echo -e "\nBoot took $(cut -d' ' -f1 /proc/uptime) seconds\n"
#setsid cttyhack setuidgid 1000 sh
setsid cttyhack setuidgid 0 sh

umount /proc
umount /sys
poweroff -d 0  -f

